name: fgm_lyrics_app
description: "A Flutter app for browsing and sharing lyrics, supporting multiple languages and modern UI."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  share_plus: ^12.0.0
  flutter_riverpod: ^3.0.1
  flutter_gutter: ^2.2.0
  audioplayers: ^6.5.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  phone_form_field: ^10.0.11+13
  http: ^1.5.0
  json_annotation: ^4.9.0
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.11.1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/en.json
    - assets/fr.json
    - assets/logo.png
    - assets/logo_pay.png
    - assets/songs/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true # Remove alpha channel for iOS App Store compliance
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0288D1"
    theme_color: "#0288D1"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"